# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7129dde50d9f9f4ff7a65798a144c399d6306e593a3ccafb34fc9f2f8bb45caf58bc59989dd3e0588f315016a814dd531a60b61e0f3851217f1fab46cd5bb0

test:
  secret_key_base: 4510e4375390561fa892e187d68ee827e419954b0d2dc91bd2d062e9d6f00208ab285d71e119266391a8be783883a7b3e9b2f3578f73c308c83cee29b78f1f33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
